apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jenkins-viewer
  namespace: jenkins-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    password: AgARIRHwsL9CHSiA7evxFLqd+bQebE6zB1L8xWYUKsZ/3B/kaW8S2G8ucOlXbRxCI1qetIKuXw3rYsM4yUzLKsU13oqjjJ9lfMH+nRf3eZx638GPATrTCFZ1WkHN563raZRjRge114r2x13pAwYbuDTXkWXxojYTeKzbgsC9fEbGEYM65Dzits4WQsD8blaWQpafMkvhF8S0Q5x6NQCG6kTcnNR+9qv1VYy07VCog/cFy294a6uOKWApkv84caW1k07NuY0zupqHzk4yVeUf6ap1EE1IHqxp+Yr/qFcqlUBiEsPFSNI1GuAKxmWnSbaHOX4GHEOqLrOpwxQ8q8B4kMWQ20BHkObSfT9SNMZeTsjHZ5obmulNv54CYhMjTDYpaL4JAZ0mqOkEcuFwJWpSpWftIc8HiwaTT52jd0gqepdHc/fhybNY8prPjVAK4fiTllV+xUz38xn0QqQLpYjmbXq7UMASXcB2Xl617YhxkYJL6MYo9+Czy2KXos+2c+v9POhpge9eJLg4zIV8ivXtHDv1KpSOPbx5fIsUL44xj9FnCaykWFfn0mydbrNqB4KLHlg9LK3i2Y9k6ZF0MdH1PKsv9NArJDylRyrpcJ8IH8X/DT7a6q9gk2Vn4dVwwXrvZnZYG+Th4hHWKBuZNa/LaE8dk44UR88aj3AEpYf6JxOs1zMjzrmKVU0wPYzQxqI/Mfmj58OxzjqUVZ3rVE/mjTEIVr0Z1owPYCjKUsxQlLPslp0TaK4ksolUD7DTnA==
  template:
    metadata:
      name: jenkins-viewer
      namespace: jenkins-gitops
