apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jenkins-automation
  namespace: jenkins-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    password: AgAKN2slFSsT9bnlAj28j21GMK1pjRl6O/fybbKTRA+F8Or48DC1Dpe93ricFOtaobhOKNofRF0XVY5cIKcbOS7OkF4oolIm0wRlefuBleEpOki7PXcYqnhCLFzJXwv+DREeWnx/8iMPIJCadCZBDUN3nfIPPkkwJJWtsec8wBi1qZGh20PLgGvXFaGPslDpJOXca5Yl+YZ6oQg2DTm1oKk7SKhXdjm1VEjfDylVf7L83BtlvfJhiM/7Y1s4qYiHV8ktro5XwI19hQrwlT/WlGSR9ev4GLLXsZGBgnSamGD5ciEVvGiCY3hz7/B+eRlIuDuK3zSHT6H1P/p+9JeoJ6Mi9/tCKXS85NELoJciJQ0ANyPD5hScgObcCufs0Ao0Q92MLKUu2lepypSJ42tIJ/m41aQ4NhUeYVN3fbjCnafEiWEXleuZmh/comEAZ1zWNlFdUCyNjp6h3ki1ixle8pvOrXSy4PRtj5kIsDBcHK28Tst5aWnd0UB0+FP1LFUeRKfbiHmiCFv1hM5z0pwbjxKRKruANAolxiAtG/Luo71hSFTXDyA71tgkt7bAcOCSCYQ04TponpoNx649ldEAUmUYG8YCFY5snmS1txuCZJPGC3CHM4vMiUUXWiAw2UjpBon80V0zjEN4nxeOjpFzkTlYwlsmVLjgfgyX0/+ddO73hIaOWEq7ToiwJud0Q69ggE2pD9A0Jn1alMdFs+K40WSqzDPlVNnfwyXZRHe1xUWkzXTVCGX9FgGkcZLtFw==
  template:
    metadata:
      name: jenkins-automation
      namespace: jenkins-gitops
