apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jenkins-smee
  namespace: jenkins-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    url: AgCnizQjsKsiMacoxErVT1QtP4wm7WlU2ht46uWp7OrJgkP5OmAM1d6yc5fYb71N45PBzVbO4p48CmVZmeV31XnfpDD7cMuuz2zzl4G1Tz5OdXGm9ONmAWqf+BPWgVZwx7imgUNkezgJcjYYUTk1ZxT4YUL3NbT2hXdeavlunIJb3A8LvdrK9pO+wjCQPRWRXrzUb8G3Xz74Id70M6NJWVd0wNIQzcwsPc3OHWEY3aGkroi7KC0SqZgzEHvYFcqhpycz5n0g+NRaB8lSOLwpB3EZqil7uvqO5g9naEeLOyGzlt1ajFcW8w37uWYDx4E7XPvYKT0uvunlTo/rdgtp6LliHPRKCbGzwKptOeMZvNGiQQVrPG+8MP7Y4kJTwrObdrpS1hqtf0o4TaEnFo8I759suH35oBMUnoxxqi+KydswPIBHMB1u5RH+XLWMZNJiZFsCX9sb13Y1KGVuwUuaDF1bWHVW51DiOdYofY6aFAZnnN3bxm+FwL+D0TRL2T4K3jjytSG/IN458ecuBZRaWHNXOSOODo+PciCNlt5TCtBlxgAFkQZ1E17G6Hma+UeoR89ttJc+dihBnTkRQ2Gf0qz2C/CSmGFJt76DlLBeZ04ZlkOGIP/vEkh5xuy+7Kmh4WZH6AUy02AL6QVVAOfC2KZIIEFCSp0yFzBnlG0kiMZ63Rix5OUEGhs7pGlQImkVRHU/hFEf26uKbyIOzd7AB6bf6cesN+vdr8f63cvN9ZQ=
  template:
    metadata:
      name: jenkins-smee
      namespace: jenkins-gitops
