apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jenkins-smee
  namespace: jenkins-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    url: AgCih62BjZTGvlcb+FYQZnhd6Rhc4YSd4s4Bd6wKREd+5N+u3gAs5fjoN2tWy6fX1qdWuw+S3Ulk6TsUMKcXkJpUKJc18zPTrB1ZLjFRQT+L2FW0omaINPWslPFzCF4Rkga4fLCbm+BRsEZ2B57uMxvxVSQDSX4yGE89Z+p09p6U42VpyjRkzgv8aNIlYPSKTdGgo6SvSAofnT6HGSDEaHffMzcT/ssluygc5wr9CnHFuDXN4b++oItm11/egjmtgrCgItiEVRvlKwJ/eGgvl83IpWf8xUnN269GLBnlzUb7KBShILf8S2FGM2KOLjcTPthx3qR4cRCR1X9q8QRzPV3fYRRgknSQo/9eodoNoG5bXCpJ6don+8F3NTcJuNGGcODWwgFmTLt0vs2uzr4Ye54ZOm/QxxEZs/jrpPxd0z1EeDvUHWz/6Wf1Lso7GvIYa9xcJRaQL1FBWVFPG8+GFc1GecRl0Cdd2zM2xZUqc7gaXCmnKdVg+CGsDI/t4dZUkXSnNmil540YvpuscK871Hbh6xvQEqOzZ+EZex1iMaVMDqm7xs/TbcX75SGm+aGdns80Gr11eUxsrohciupRRvdzDhtczmxb7/Jb1JTDjwGD6D4REOeeCRzGJLf3a7P8YLatdKfZUMLW0vi45MY7Xutt2yM7I1RplyhgIpb01YLLjcxhUp77UOMzuRo0Z9EQ/bb9OTBUSih7xlaDmlTipbby2N/JB6Fx5MOItfEV+ML6OQ==
  template:
    metadata:
      name: jenkins-smee
      namespace: jenkins-gitops
