apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jenkins-registry
  namespace: jenkins-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    .dockerconfigjson: AgA6ESzpU/1+9f6veeTOahmCzBTOBgLNv6R23zLBT370E4pr9bBdZzOybu5h1b9mK8Mwgs9Yfr9pnLEZ6VE3oUtWtOPYQslGEM9ib1b/0yVo662D6WlYhUCAHXL2ZVH4r/Lriv/NqBw1gRlDNNgeivRSJRsbRVw9bD57C/FHj/ljYrKzeiJj22gs+A62089aI3zBNc8/GaHn7Hs8eSCF+clWvgPuj+oAtHLY1H5NxC0AsuJQOb53mUogKwlLeroiZHQ6v4POSA4fz8RUsvPwgqYzwuBMt02Zj3f2nlPb9xYAh1Gfa6VI3/zEVr/2PaTIZIeIy9nfj4UnXh/QZNUqM2hZDtV3OGKCXQbLDbjrmSoLxYky1fu9daugnGHW6MW+ooijVZz0gHKifqVxjVfgEhuD2dw38YdQueUP353CDg/F7dymHXzctAlSOYu+6Ba+tusPh/BqtyTkCRstPla2zz+P1bUxMdGxlTsO9zJwOVlfzH7JnatmvRU0UPqW9YK5q/xfV6nVrUyh0WosOVi7xOqJyqg1mlCrRnw1+M83R3UMjCUH2DGJ/EJ7QJ+CDQJrZr1ERIi0sqDjCcEU/F7y3fjmsJGI+O0caAGYMOnoiQAUimc2sOZCFxfalGqMlgCJ5FQUTD0HityfgnOzNc4t7Ap8ius+xT+13N059UzQ8SgLpnldtwm4mbr9iCoG+XDc31OSmOZjaEPYZ8ouafqCUTiWP+NlN0BehDrpXNai3AABaNj7yOgKSc6qDn1zDYDRlPmqEDkMnAoXS6t9yx5VDqyn/VLVEFxPd+zwst43I5n+Y/5w2HLLbJ3eetZod6aSFlgYHTyT
  template:
    metadata:
      name: jenkins-registry
      namespace: jenkins-gitops
    type: kubernetes.io/dockerconfigjson
