apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jenkins-slack
  namespace: jenkins-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    url: AgBIhqyzPNjph02ZPcEutSP9N1NObg0T1S0faioJB5XUBPhEyTcwvSEc89F2AYPF/ry/KwTQKB9OjHrUVVuAGSQaKr3XV0NJ1u4nI8Z/qDt8mD+3468lngcABzmrZsbXrHzx1DEWYhLo2zV+b5VMRtzfrAnAA/fm7mpKBRunTyziZ9/WL4P5VHD5mmZsy2uGyubrpPISZx7eqtpr9ruSCC9AQUu50zw74F1bBsTM4azNu8th+T91MRHaLC2SvYyE/quYTDfpaki65AFniSLjy42ZmPSIPHNwVCfvF0CTkPo+HxjYIZ/V/r/ZVRybOSfxKx9OElBLBlCCf1lIWUphvzMGaZrtczslHAPltBDdV5cYVfQCwWLgGgwoVylfyrdkBTQMtU55rxlF1xCvYKr6nQG1QOPEc6UxhaAYKpaDeap7ODaw61Euxw5D8bhbpO5REK1+amC5LULaK6T793m0A1cGoP7++OrfejqA23UN+QnvbhyulSCQInhp4uTsJwFE+UAUk2nnL0pjzRe+X7aP070MUg6dO6IhmM73KvUvRR0nZC5nXvbyEgv107sSkGHdqEzcVxZZYMGm1FWaEkYlBTmwWKxSQ9j1pUHEtsQaYKjymzrpxYyjpR9fStjgZJCA/aZEv2c3y9OtpoWS3aTlf+eSBms79Fj5XXaKhW4uRFEd3sfEfRZCdbTSXEjzPegZFjz8A23dn6APP2mrTMso3htCFrl9axfxcwGS1G4IUhoeveX+vyGdHRGOo3XTfP20HfImVStFNnY7aD8/yxTgKdXQhye8CvEjwrR9I17mvidXm1M=
  template:
    metadata:
      name: jenkins-slack
      namespace: jenkins-gitops
