---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-slack-webhook
  namespace: monitoring
spec:
  encryptedData:
    url: AgAGdaPEAnpGeJor7+rGkLjwdV//WC+sfMs3Itm6FNAbg9ZZ+gIiWjyF2ArTREXVKL/k/Tu8b+2GWc/Ld9eFqTDDH7tMFUdzcO8BqGRdpqJkseo+u3YiVLLiaYY5P9WwV/vU1XO1fE7EjwOvcYEO0jXKTSqmq8yz/1x6l3b7Qzuz4uNcQsKFxrw8MugdGkxJ194UdAzBZ0FV8xShPqDY5iL6ywh9PMCcHbmNIV9BaBIMXQ3Yw8Xv2sKGzbhBrrGFTx+wjLUuPfMETeDVAscqiRD0a38kJWUNsxJ4FcIm0YB2R67rFZSK9U7OqW5GaWM3ZMeq4TzpGYKQ8xUxPfHWmTkOLPJ4e3t1rIDBvSGsBNLjRrJIlsNYl+tCA9kJPoNeMTUXpvuRoGhH4Hwk/XtOBdjw9XHHiXGJT5BeWnlC4uju/qea6gXOdR8xZ/NggCU3qvSaIw2TWSnpi7+K5TPU851bnMkGF+GLV3F9ndtN2DAZfhfJT3Nni9CpD1jbEBgg05YGVz3aReBKSOMUqx5BCY/MNEA5zUya8sDlqwNP8Tf15Y7NoZZ1hTLP9UTmiSWY73B7y6ESIE62ixdKZBGQ/wqt53HTKVrK09SfT5umtmNSkxJkNlg+sD/J50W9tWkaFmIyC/5Cv5WchJBKeG4R1ueZ8zxq0MIcbMskAziWdCP6GtJTjI2SSW4BNV4wWmq+jwAqjThqqGpxujmDhP219o0acO0YaSi/Qj72N+uHUqqrB5ljD0pSg5Te8kkirs/TXfwRdodqxvKhOX286kgmRKX3TwNRvtgIK3TmM84fbjfJoVg=
  template:
    metadata:
      name: alertmanager-slack-webhook
      namespace: monitoring
